window.defaultWords = [
  // --- Bridge A2 - Lesson 08 ---
  { id: "a2_l08_01", word: "exhausted", pos: "adjective", definition: "기진맥진한", level: "Bridge A2", lesson: "Lesson 08", lessonTitle: "" },
  { id: "a2_l08_02", word: "get through", pos: "verb", definition: "겪어내다", level: "Bridge A2", lesson: "Lesson 08", lessonTitle: "" },
  { id: "a2_l08_03", word: "startled", pos: "adjective", definition: "깜짝 놀란", level: "Bridge A2", lesson: "Lesson 08", lessonTitle: "" },
  { id: "a2_l08_04", word: "refreshment", pos: "noun", definition: "원기 충전", level: "Bridge A2", lesson: "Lesson 08", lessonTitle: "" },
  { id: "a2_l08_05", word: "ingredient", pos: "noun", definition: "재료", level: "Bridge A2", lesson: "Lesson 08", lessonTitle: "" },
  { id: "a2_l08_06", word: "enormous", pos: "adjective", definition: "막대한", level: "Bridge A2", lesson: "Lesson 08", lessonTitle: "" },
  { id: "a2_l08_07", word: "burst", pos: "noun", definition: "터뜨림", level: "Bridge A2", lesson: "Lesson 08", lessonTitle: "" },
  { id: "a2_l08_08", word: "come crashing down", pos: "verb", definition: "무너지다", level: "Bridge A2", lesson: "Lesson 08", lessonTitle: "" },
  { id: "a2_l08_09", word: "nutritional", pos: "adjective", definition: "영양의", level: "Bridge A2", lesson: "Lesson 08", lessonTitle: "" },
  { id: "a2_l08_10", word: "exotic", pos: "adjective", definition: "이국적인", level: "Bridge A2", lesson: "Lesson 08", lessonTitle: "" },
  { id: "a2_l08_11", word: "sweeten", pos: "verb", definition: "달게 만들다", level: "Bridge A2", lesson: "Lesson 08", lessonTitle: "" },
  { id: "a2_l08_12", word: "academic", pos: "adjective", definition: "학업의", level: "Bridge A2", lesson: "Lesson 08", lessonTitle: "" },
  { id: "a2_l08_13", word: "acquaintance", pos: "noun", definition: "지인", level: "Bridge A2", lesson: "Lesson 08", lessonTitle: "" },
  { id: "a2_l08_14", word: "rely on", pos: "verb", definition: "의존하다", level: "Bridge A2", lesson: "Lesson 08", lessonTitle: "" },
  { id: "a2_l08_15", word: "former", pos: "adjective", definition: "이전의", level: "Bridge A2", lesson: "Lesson 08", lessonTitle: "" },
  { id: "a2_l08_16", word: "inspire", pos: "verb", definition: "영감을 주다", level: "Bridge A2", lesson: "Lesson 08", lessonTitle: "" },
  { id: "a2_l08_17", word: "encourage", pos: "verb", definition: "북돋다", level: "Bridge A2", lesson: "Lesson 08", lessonTitle: "" },
  { id: "a2_l08_18", word: "ambitious", pos: "adjective", definition: "야심만만한", level: "Bridge A2", lesson: "Lesson 08", lessonTitle: "" },
  { id: "a2_l08_19", word: "carry out", pos: "verb", definition: "실시하다", level: "Bridge A2", lesson: "Lesson 08", lessonTitle: "" },
  { id: "a2_l08_20", word: "obedience", pos: "noun", definition: "복종", level: "Bridge A2", lesson: "Lesson 08", lessonTitle: "" },
  { id: "a2_l08_21", word: "mislead", pos: "verb", definition: "잘못된 방향으로 이끌다", level: "Bridge A2", lesson: "Lesson 08", lessonTitle: "" },
  { id: "a2_l08_22", word: "come up with", pos: "verb", definition: "생각해내다", level: "Bridge A2", lesson: "Lesson 08", lessonTitle: "" },
  { id: "a2_l08_23", word: "controversial", pos: "adjective", definition: "논란이 많은", level: "Bridge A2", lesson: "Lesson 08", lessonTitle: "" },
  { id: "a2_l08_24", word: "obey", pos: "verb", definition: "따르다", level: "Bridge A2", lesson: "Lesson 08", lessonTitle: "" },
  { id: "a2_l08_25", word: "punishment", pos: "noun", definition: "벌", level: "Bridge A2", lesson: "Lesson 08", lessonTitle: "" },
  { id: "a2_l08_26", word: "technician", pos: "noun", definition: "기술자", level: "Bridge A2", lesson: "Lesson 08", lessonTitle: "" },
  { id: "a2_l08_27", word: "permission", pos: "noun", definition: "허락", level: "Bridge A2", lesson: "Lesson 08", lessonTitle: "" },
  { id: "a2_l08_28", word: "prop", pos: "noun", definition: "소품", level: "Bridge A2", lesson: "Lesson 08", lessonTitle: "" },
  { id: "a2_l08_29", word: "authority figure", pos: "noun", definition: "권위자", level: "Bridge A2", lesson: "Lesson 08", lessonTitle: "" },
  { id: "a2_l08_30", word: "sore", pos: "adjective", definition: "아픈", level: "Bridge A2", lesson: "Lesson 08", lessonTitle: "" },
  { id: "a2_l08_31", word: "stiff", pos: "adjective", definition: "뻣뻣한", level: "Bridge A2", lesson: "Lesson 08", lessonTitle: "" },
  { id: "a2_l08_32", word: "delayed", pos: "adjective", definition: "지연된", level: "Bridge A2", lesson: "Lesson 08", lessonTitle: "" },
  { id: "a2_l08_33", word: "strenuous", pos: "adjective", definition: "격렬한", level: "Bridge A2", lesson: "Lesson 08", lessonTitle: "" },
  { id: "a2_l08_34", word: "temporarily", pos: "adverb", definition: "임시로", level: "Bridge A2", lesson: "Lesson 08", lessonTitle: "" },
  { id: "a2_l08_35", word: "alleviate", pos: "verb", definition: "완화하다", level: "Bridge A2", lesson: "Lesson 08", lessonTitle: "" },
  { id: "a2_l08_36", word: "go away", pos: "verb", definition: "사라지다", level: "Bridge A2", lesson: "Lesson 08", lessonTitle: "" },
  { id: "a2_l08_37", word: "intensity", pos: "noun", definition: "강도", level: "Bridge A2", lesson: "Lesson 08", lessonTitle: "" },
  { id: "a2_l08_38", word: "adapt", pos: "verb", definition: "적응하다", level: "Bridge A2", lesson: "Lesson 08", lessonTitle: "" },
  { id: "a2_l08_39", word: "deceive", pos: "verb", definition: "속이다", level: "Bridge A2", lesson: "Lesson 08", lessonTitle: "" },
  { id: "a2_l08_40", word: "observe", pos: "verb", definition: "관찰하다", level: "Bridge A2", lesson: "Lesson 08", lessonTitle: "" },
  { id: "a2_l08_41", word: "dig up", pos: "verb", definition: "캐내다", level: "Bridge A2", lesson: "Lesson 08", lessonTitle: "" },
  { id: "a2_l08_42", word: "garbage", pos: "noun", definition: "쓰레기", level: "Bridge A2", lesson: "Lesson 08", lessonTitle: "" },
  { id: "a2_l08_43", word: "formation", pos: "noun", definition: "형성", level: "Bridge A2", lesson: "Lesson 08", lessonTitle: "" },
  { id: "a2_l08_44", word: "definitely", pos: "adverb", definition: "분명히", level: "Bridge A2", lesson: "Lesson 08", lessonTitle: "" },
  { id: "a2_l08_45", word: "Empire", pos: "noun", definition: "제국", level: "Bridge A2", lesson: "Lesson 08", lessonTitle: "" },
  { id: "a2_l08_46", word: "continent", pos: "noun", definition: "대륙", level: "Bridge A2", lesson: "Lesson 08", lessonTitle: "" },
  { id: "a2_l08_47", word: "attempt", pos: "noun", definition: "시도", level: "Bridge A2", lesson: "Lesson 08", lessonTitle: "" },
  { id: "a2_l08_48", word: "bedridden", pos: "adjective", definition: "몸져누운", level: "Bridge A2", lesson: "Lesson 08", lessonTitle: "" },
  { id: "a2_l08_49", word: "typical", pos: "adjective", definition: "보통의", level: "Bridge A2", lesson: "Lesson 08", lessonTitle: "" },
  { id: "a2_l08_50", word: "dull", pos: "adjective", definition: "둔한", level: "Bridge A2", lesson: "Lesson 08", lessonTitle: "" },
  { id: "a2_l08_51", word: "throb", pos: "verb", definition: "욱신거리다", level: "Bridge A2", lesson: "Lesson 08", lessonTitle: "" },
  { id: "a2_l08_52", word: "stab", pos: "verb", definition: "찌르다", level: "Bridge A2", lesson: "Lesson 08", lessonTitle: "" },
  { id: "a2_l08_53", word: "run in the family", pos: "verb", definition: "집안 내력이다", level: "Bridge A2", lesson: "Lesson 08", lessonTitle: "" },
  { id: "a2_l08_54", word: "carbohydrate", pos: "noun", definition: "탄수화물", level: "Bridge A2", lesson: "Lesson 08", lessonTitle: "" },
  { id: "a2_l08_55", word: "alternative", pos: "adjective", definition: "대체의", level: "Bridge A2", lesson: "Lesson 08", lessonTitle: "" },
  { id: "a2_l08_56", word: "immediate", pos: "adjective", definition: "즉각적인", level: "Bridge A2", lesson: "Lesson 08", lessonTitle: "" },
  { id: "a2_l08_57", word: "revolve", pos: "verb", definition: "회전하다", level: "Bridge A2", lesson: "Lesson 08", lessonTitle: "" },
  { id: "a2_l08_58", word: "drought", pos: "noun", definition: "가뭄", level: "Bridge A2", lesson: "Lesson 08", lessonTitle: "" },
  { id: "a2_l08_59", word: "phenomenon", pos: "noun", definition: "현상", level: "Bridge A2", lesson: "Lesson 08", lessonTitle: "" },
  { id: "a2_l08_60", word: "frightening", pos: "adjective", definition: "무서운", level: "Bridge A2", lesson: "Lesson 08", lessonTitle: "" },

  // --- Bridge A2 - Lesson 09 ---
  { id: "a2_l09_01", word: "ensure", pos: "verb", definition: "보장하다", level: "Bridge A2", lesson: "Lesson 09", lessonTitle: "" },
  { id: "a2_l09_02", word: "involved", pos: "adjective", definition: "연루된", level: "Bridge A2", lesson: "Lesson 09", lessonTitle: "" },
  { id: "a2_l09_03", word: "electronic", pos: "adjective", definition: "전자의", level: "Bridge A2", lesson: "Lesson 09", lessonTitle: "" },
  { id: "a2_l09_04", word: "on behalf of", pos: "preposition", definition: "대표하여", level: "Bridge A2", lesson: "Lesson 09", lessonTitle: "" },
  { id: "a2_l09_05", word: "elective", pos: "adjective", definition: "선택의", level: "Bridge A2", lesson: "Lesson 09", lessonTitle: "" },
  { id: "a2_l09_06", word: "modify", pos: "verb", definition: "수정하다", level: "Bridge A2", lesson: "Lesson 09", lessonTitle: "" },
  { id: "a2_l09_07", word: "semester", pos: "noun", definition: "학기", level: "Bridge A2", lesson: "Lesson 09", lessonTitle: "" },
  { id: "a2_l09_08", word: "come under fire", pos: "preposition", definition: "비난을 받다", level: "Bridge A2", lesson: "Lesson 09", lessonTitle: "" },
  { id: "a2_l09_09", word: "obesity", pos: "noun", definition: "비만", level: "Bridge A2", lesson: "Lesson 09", lessonTitle: "" },
  { id: "a2_l09_10", word: "overweight", pos: "adjective", definition: "과체중의", level: "Bridge A2", lesson: "Lesson 09", lessonTitle: "" },
  { id: "a2_l09_11", word: "process", pos: "verb", definition: "가공하다", level: "Bridge A2", lesson: "Lesson 09", lessonTitle: "" },
  { id: "a2_l09_12", word: "nutrition", pos: "noun", definition: "영양", level: "Bridge A2", lesson: "Lesson 09", lessonTitle: "" },
  { id: "a2_l09_13", word: "flavored", pos: "adjective", definition: "맛이 첨가된", level: "Bridge A2", lesson: "Lesson 09", lessonTitle: "" },
  { id: "a2_l09_14", word: "nutrient", pos: "noun", definition: "영양소", level: "Bridge A2", lesson: "Lesson 09", lessonTitle: "" },
  { id: "a2_l09_15", word: "bill", pos: "noun", definition: "법안", level: "Bridge A2", lesson: "Lesson 09", lessonTitle: "" },
  { id: "a2_l09_16", word: "approve", pos: "verb", definition: "승인하다", level: "Bridge A2", lesson: "Lesson 09", lessonTitle: "" },
  { id: "a2_l09_17", word: "veto", pos: "verb", definition: "거부하다", level: "Bridge A2", lesson: "Lesson 09", lessonTitle: "" },
  { id: "a2_l09_18", word: "override", pos: "verb", definition: "무효화하다", level: "Bridge A2", lesson: "Lesson 09", lessonTitle: "" },
  { id: "a2_l09_19", word: "assume", pos: "verb", definition: "추정하다", level: "Bridge A2", lesson: "Lesson 09", lessonTitle: "" },
  { id: "a2_l09_20", word: "ethnic", pos: "adjective", definition: "민족의", level: "Bridge A2", lesson: "Lesson 09", lessonTitle: "" },
  { id: "a2_l09_21", word: "accustomed", pos: "adjective", definition: "익숙한", level: "Bridge A2", lesson: "Lesson 09", lessonTitle: "" },
  { id: "a2_l09_22", word: "capacity", pos: "noun", definition: "용량", level: "Bridge A2", lesson: "Lesson 09", lessonTitle: "" },
  { id: "a2_l09_23", word: "supplement", pos: "verb", definition: "보충하다", level: "Bridge A2", lesson: "Lesson 09", lessonTitle: "" },
  { id: "a2_l09_24", word: "account for", pos: "preposition", definition: "차지하다", level: "Bridge A2", lesson: "Lesson 09", lessonTitle: "" },
  { id: "a2_l09_25", word: "outgrow", pos: "verb", definition: "벗어나다", level: "Bridge A2", lesson: "Lesson 09", lessonTitle: "" },
  { id: "a2_l09_26", word: "immune", pos: "adjective", definition: "면역의", level: "Bridge A2", lesson: "Lesson 09", lessonTitle: "" },
  { id: "a2_l09_27", word: "antibody", pos: "noun", definition: "항체", level: "Bridge A2", lesson: "Lesson 09", lessonTitle: "" },
  { id: "a2_l09_28", word: "offending", pos: "adjective", definition: "불쾌감을 주는", level: "Bridge A2", lesson: "Lesson 09", lessonTitle: "" },
  { id: "a2_l09_29", word: "consume", pos: "verb", definition: "소비하다", level: "Bridge A2", lesson: "Lesson 09", lessonTitle: "" },
  { id: "a2_l09_30", word: "trigger", pos: "verb", definition: "일으키다", level: "Bridge A2", lesson: "Lesson 09", lessonTitle: "" },
  { id: "a2_l09_31", word: "deadly", pos: "adjective", definition: "치명적인", level: "Bridge A2", lesson: "Lesson 09", lessonTitle: "" },
  { id: "a2_l09_32", word: "medication", pos: "noun", definition: "약", level: "Bridge A2", lesson: "Lesson 09", lessonTitle: "" },
  { id: "a2_l09_33", word: "organic", pos: "adjective", definition: "유기의", level: "Bridge A2", lesson: "Lesson 09", lessonTitle: "" },
  { id: "a2_l09_34", word: "plot", pos: "noun", definition: "작은 땅", level: "Bridge A2", lesson: "Lesson 09", lessonTitle: "" },
  { id: "a2_l09_35", word: "lane", pos: "noun", definition: "차선", level: "Bridge A2", lesson: "Lesson 09", lessonTitle: "" },
  { id: "a2_l09_36", word: "pollution", pos: "noun", definition: "오염", level: "Bridge A2", lesson: "Lesson 09", lessonTitle: "" },
  { id: "a2_l09_37", word: "legibly", pos: "adverb", definition: "알아보기 쉽게", level: "Bridge A2", lesson: "Lesson 09", lessonTitle: "" },
  { id: "a2_l09_38", word: "concise", pos: "adjective", definition: "간결한", level: "Bridge A2", lesson: "Lesson 09", lessonTitle: "" },
  { id: "a2_l09_39", word: "come down with", pos: "preposition", definition: "걸리다", level: "Bridge A2", lesson: "Lesson 09", lessonTitle: "" },
  { id: "a2_l09_40", word: "chickenpox", pos: "noun", definition: "수두", level: "Bridge A2", lesson: "Lesson 09", lessonTitle: "" },
  { id: "a2_l09_41", word: "contagious", pos: "adjective", definition: "전염성의", level: "Bridge A2", lesson: "Lesson 09", lessonTitle: "" },
  { id: "a2_l09_42", word: "precautionary", pos: "adjective", definition: "예방의", level: "Bridge A2", lesson: "Lesson 09", lessonTitle: "" },
  { id: "a2_l09_43", word: "scrap", pos: "noun", definition: "고물", level: "Bridge A2", lesson: "Lesson 09", lessonTitle: "" },
  { id: "a2_l09_44", word: "fulfill", pos: "verb", definition: "이행하다", level: "Bridge A2", lesson: "Lesson 09", lessonTitle: "" },
  { id: "a2_l09_45", word: "administration", pos: "noun", definition: "행정", level: "Bridge A2", lesson: "Lesson 09", lessonTitle: "" },
  { id: "a2_l09_46", word: "attendance", pos: "noun", definition: "출석", level: "Bridge A2", lesson: "Lesson 09", lessonTitle: "" },
  { id: "a2_l09_47", word: "away", pos: "adjective", definition: "원정의", level: "Bridge A2", lesson: "Lesson 09", lessonTitle: "" },
  { id: "a2_l09_48", word: "construction", pos: "noun", definition: "건설", level: "Bridge A2", lesson: "Lesson 09", lessonTitle: "" },
  { id: "a2_l09_49", word: "transparent", pos: "adjective", definition: "투명한", level: "Bridge A2", lesson: "Lesson 09", lessonTitle: "" },
  { id: "a2_l09_50", word: "costume", pos: "noun", definition: "복장", level: "Bridge A2", lesson: "Lesson 09", lessonTitle: "" },
  { id: "a2_l09_51", word: "replacement", pos: "noun", definition: "대신할 사람", level: "Bridge A2", lesson: "Lesson 09", lessonTitle: "" },
  { id: "a2_l09_52", word: "textile", pos: "noun", definition: "직물", level: "Bridge A2", lesson: "Lesson 09", lessonTitle: "" },
  { id: "a2_l09_53", word: "weave", pos: "verb", definition: "짜다", level: "Bridge A2", lesson: "Lesson 09", lessonTitle: "" },
  { id: "a2_l09_54", word: "dual", pos: "adjective", definition: "이중의", level: "Bridge A2", lesson: "Lesson 09", lessonTitle: "" },
  { id: "a2_l09_55", word: "persecution", pos: "noun", definition: "박해", level: "Bridge A2", lesson: "Lesson 09", lessonTitle: "" },
  { id: "a2_l09_56", word: "infamous", pos: "adjective", definition: "악명 높은", level: "Bridge A2", lesson: "Lesson 09", lessonTitle: "" },
  { id: "a2_l09_57", word: "beverage", pos: "noun", definition: "음료", level: "Bridge A2", lesson: "Lesson 09", lessonTitle: "" },
  { id: "a2_l09_58", word: "spark", pos: "verb", definition: "불러일으키다", level: "Bridge A2", lesson: "Lesson 09", lessonTitle: "" },
  { id: "a2_l09_59", word: "height", pos: "noun", definition: "절정", level: "Bridge A2", lesson: "Lesson 09", lessonTitle: "" },
  { id: "a2_l09_60", word: "depict", pos: "verb", definition: "묘사하다", level: "Bridge A2", lesson: "Lesson 09", lessonTitle: "" },

  // --- Bridge A2 - Lesson 10 ---
  { id: "a2_l10_01", word: "hover in the air", pos: "verb", definition: "떠 있다", level: "Bridge A2", lesson: "Lesson 10", lessonTitle: "" },
  { id: "a2_l10_02", word: "British colony", pos: "noun", definition: "식민지", level: "Bridge A2", lesson: "Lesson 10", lessonTitle: "" },
  { id: "a2_l10_03", word: "upcoming holiday season", pos: "adjective", definition: "다가오는", level: "Bridge A2", lesson: "Lesson 10", lessonTitle: "" },
  { id: "a2_l10_04", word: "fluctuate in price", pos: "verb", definition: "변동을 거듭하다", level: "Bridge A2", lesson: "Lesson 10", lessonTitle: "" },
  { id: "a2_l10_05", word: "political circumstances", pos: "noun", definition: "상황", level: "Bridge A2", lesson: "Lesson 10", lessonTitle: "" },
  { id: "a2_l10_06", word: "suffer from insomnia", pos: "noun", definition: "불면증", level: "Bridge A2", lesson: "Lesson 10", lessonTitle: "" },
  { id: "a2_l10_07", word: "flu symptom", pos: "noun", definition: "증상", level: "Bridge A2", lesson: "Lesson 10", lessonTitle: "" },
  { id: "a2_l10_08", word: "reveal the truth", pos: "verb", definition: "밝히다", level: "Bridge A2", lesson: "Lesson 10", lessonTitle: "" },
  { id: "a2_l10_09", word: "chemical change", pos: "adjective", definition: "화학의", level: "Bridge A2", lesson: "Lesson 10", lessonTitle: "" },
  { id: "a2_l10_10", word: "construct a theory", pos: "verb", definition: "세우다", level: "Bridge A2", lesson: "Lesson 10", lessonTitle: "" },
  { id: "a2_l10_11", word: "precise measurement", pos: "adjective", definition: "정확한", level: "Bridge A2", lesson: "Lesson 10", lessonTitle: "" },
  { id: "a2_l10_12", word: "data analysis", pos: "noun", definition: "분석", level: "Bridge A2", lesson: "Lesson 10", lessonTitle: "" },
  { id: "a2_l10_13", word: "transmit a disease", pos: "verb", definition: "전염시키다", level: "Bridge A2", lesson: "Lesson 10", lessonTitle: "" },
  { id: "a2_l10_14", word: "cold remedy", pos: "noun", definition: "약", level: "Bridge A2", lesson: "Lesson 10", lessonTitle: "" },
  { id: "a2_l10_15", word: "cause inconvenience", pos: "noun", definition: "불편", level: "Bridge A2", lesson: "Lesson 10", lessonTitle: "" },
  { id: "a2_l10_16", word: "independent country", pos: "adjective", definition: "독립된", level: "Bridge A2", lesson: "Lesson 10", lessonTitle: "" },
  { id: "a2_l10_17", word: "owner's permission", pos: "noun", definition: "허락", level: "Bridge A2", lesson: "Lesson 10", lessonTitle: "" },
  { id: "a2_l10_18", word: "occupy a large space", pos: "verb", definition: "차지하다", level: "Bridge A2", lesson: "Lesson 10", lessonTitle: "" },
  { id: "a2_l10_19", word: "athletics coach", pos: "noun", definition: "운동", level: "Bridge A2", lesson: "Lesson 10", lessonTitle: "" },
  { id: "a2_l10_20", word: "submit homework", pos: "verb", definition: "제출하다", level: "Bridge A2", lesson: "Lesson 10", lessonTitle: "" },
  { id: "a2_l10_21", word: "disturb a class", pos: "verb", definition: "방해하다", level: "Bridge A2", lesson: "Lesson 10", lessonTitle: "" },
  { id: "a2_l10_22", word: "cholera outbreak", pos: "noun", definition: "발병", level: "Bridge A2", lesson: "Lesson 10", lessonTitle: "" },
  { id: "a2_l10_23", word: "local resident", pos: "noun", definition: "주민", level: "Bridge A2", lesson: "Lesson 10", lessonTitle: "" },
  { id: "a2_l10_24", word: "donate to a charity", pos: "noun", definition: "자선 단체", level: "Bridge A2", lesson: "Lesson 10", lessonTitle: "" },
  { id: "a2_l10_25", word: "retrieve the lost watch", pos: "verb", definition: "되찾다", level: "Bridge A2", lesson: "Lesson 10", lessonTitle: "" },
  { id: "a2_l10_26", word: "virtue of patience", pos: "noun", definition: "미덕", level: "Bridge A2", lesson: "Lesson 10", lessonTitle: "" },
  { id: "a2_l10_27", word: "Roman emperor", pos: "noun", definition: "황제", level: "Bridge A2", lesson: "Lesson 10", lessonTitle: "" },
  { id: "a2_l10_28", word: "unreasonable request", pos: "adjective", definition: "불합리한", level: "Bridge A2", lesson: "Lesson 10", lessonTitle: "" },
  { id: "a2_l10_29", word: "maintain balance", pos: "verb", definition: "유지하다", level: "Bridge A2", lesson: "Lesson 10", lessonTitle: "" },
  { id: "a2_l10_30", word: "unconstitutional law", pos: "adjective", definition: "위헌의", level: "Bridge A2", lesson: "Lesson 10", lessonTitle: "" },
  { id: "a2_l10_31", word: "boost confidence", pos: "verb", definition: "북돋다", level: "Bridge A2", lesson: "Lesson 10", lessonTitle: "" },
  { id: "a2_l10_32", word: "scatter seeds", pos: "verb", definition: "흩뿌리다", level: "Bridge A2", lesson: "Lesson 10", lessonTitle: "" },
  { id: "a2_l10_33", word: "daily routine", pos: "noun", definition: "일과", level: "Bridge A2", lesson: "Lesson 10", lessonTitle: "" },
  { id: "a2_l10_34", word: "color combination", pos: "noun", definition: "조합", level: "Bridge A2", lesson: "Lesson 10", lessonTitle: "" },
  { id: "a2_l10_35", word: "complement each other perfectly", pos: "verb", definition: "보완하다", level: "Bridge A2", lesson: "Lesson 10", lessonTitle: "" },
  { id: "a2_l10_36", word: "sewer pipe", pos: "noun", definition: "하수도", level: "Bridge A2", lesson: "Lesson 10", lessonTitle: "" },
  { id: "a2_l10_37", word: "attribute success to luck", pos: "verb", definition: "~을 ~의 결과라고 생각하다", level: "Bridge A2", lesson: "Lesson 10", lessonTitle: "" },
  { id: "a2_l10_38", word: "medieval knight", pos: "adjective", definition: "중세의", level: "Bridge A2", lesson: "Lesson 10", lessonTitle: "" },
  { id: "a2_l10_39", word: "mercury poisoning", pos: "noun", definition: "수은", level: "Bridge A2", lesson: "Lesson 10", lessonTitle: "" },
  { id: "a2_l10_40", word: "ear thermometer", pos: "noun", definition: "온도계", level: "Bridge A2", lesson: "Lesson 10", lessonTitle: "" },
  { id: "a2_l10_41", word: "poisonous gas", pos: "adjective", definition: "독이 있는", level: "Bridge A2", lesson: "Lesson 10", lessonTitle: "" },
  { id: "a2_l10_42", word: "emergency rescue", pos: "noun", definition: "구조", level: "Bridge A2", lesson: "Lesson 10", lessonTitle: "" },
  { id: "a2_l10_43", word: "identical fingerprint", pos: "adjective", definition: "동일한", level: "Bridge A2", lesson: "Lesson 10", lessonTitle: "" },
  { id: "a2_l10_44", word: "Greek architecture", pos: "noun", definition: "건축", level: "Bridge A2", lesson: "Lesson 10", lessonTitle: "" },
  { id: "a2_l10_45", word: "eternal afterlife", pos: "noun", definition: "내세", level: "Bridge A2", lesson: "Lesson 10", lessonTitle: "" },
  { id: "a2_l10_46", word: "Notre-Dame Cathedral", pos: "noun", definition: "대성당", level: "Bridge A2", lesson: "Lesson 10", lessonTitle: "" },
  { id: "a2_l10_47", word: "memorize English words", pos: "verb", definition: "암기하다", level: "Bridge A2", lesson: "Lesson 10", lessonTitle: "" },
  { id: "a2_l10_48", word: "astonished and speechless", pos: "adjective", definition: "깜짝 놀란", level: "Bridge A2", lesson: "Lesson 10", lessonTitle: "" },
  { id: "a2_l10_49", word: "admission of defeat", pos: "noun", definition: "인정", level: "Bridge A2", lesson: "Lesson 10", lessonTitle: "" },
  { id: "a2_l10_50", word: "street vendor", pos: "noun", definition: "판매자", level: "Bridge A2", lesson: "Lesson 10", lessonTitle: "" },
  { id: "a2_l10_51", word: "vanish from sight", pos: "verb", definition: "사라지다", level: "Bridge A2", lesson: "Lesson 10", lessonTitle: "" },
  { id: "a2_l10_52", word: "burst into the room", pos: "verb", definition: "들이닥치다", level: "Bridge A2", lesson: "Lesson 10", lessonTitle: "" },
  { id: "a2_l10_53", word: "corporate headquarters", pos: "noun", definition: "본부", level: "Bridge A2", lesson: "Lesson 10", lessonTitle: "" },
  { id: "a2_l10_54", word: "friend and acquaintance", pos: "noun", definition: "지인", level: "Bridge A2", lesson: "Lesson 10", lessonTitle: "" },
  { id: "a2_l10_55", word: "former president", pos: "adjective", definition: "이전의", level: "Bridge A2", lesson: "Lesson 10", lessonTitle: "" },
  { id: "a2_l10_56", word: "carry out a survey", pos: "preposition", definition: "실시하다", level: "Bridge A2", lesson: "Lesson 10", lessonTitle: "" },
  { id: "a2_l10_57", word: "electrical technician", pos: "noun", definition: "기술자", level: "Bridge A2", lesson: "Lesson 10", lessonTitle: "" },
  { id: "a2_l10_58", word: "deceive the consumers", pos: "verb", definition: "속이다", level: "Bridge A2", lesson: "Lesson 10", lessonTitle: "" },
  { id: "a2_l10_59", word: "stab the meat with a knife", pos: "verb", definition: "찌르다", level: "Bridge A2", lesson: "Lesson 10", lessonTitle: "" },
  { id: "a2_l10_60", word: "protein and carbohydrate", pos: "noun", definition: "탄수화물", level: "Bridge A2", lesson: "Lesson 10", lessonTitle: "" },

  // --- Bridge A2 - Lesson 11 ---
  { id: "a2_l11_01", word: "avoid eye contact", pos: "verb", definition: "피하다", level: "Bridge A2", lesson: "Lesson 11", lessonTitle: "" },
  { id: "a2_l11_02", word: "soaked with rain", pos: "adjective", definition: "흠뻑 젖은", level: "Bridge A2", lesson: "Lesson 11", lessonTitle: "" },
  { id: "a2_l11_03", word: "refreshing night air", pos: "adjective", definition: "상쾌하게 하는", level: "Bridge A2", lesson: "Lesson 11", lessonTitle: "" },
  { id: "a2_l11_04", word: "complicated math problem", pos: "adjective", definition: "복잡한", level: "Bridge A2", lesson: "Lesson 11", lessonTitle: "" },
  { id: "a2_l11_05", word: "prestigious university", pos: "adjective", definition: "명망 있는", level: "Bridge A2", lesson: "Lesson 11", lessonTitle: "" },
  { id: "a2_l11_06", word: "praise from a teacher", pos: "noun", definition: "칭찬", level: "Bridge A2", lesson: "Lesson 11", lessonTitle: "" },
  { id: "a2_l11_07", word: "dedicated parents", pos: "adjective", definition: "헌신적인", level: "Bridge A2", lesson: "Lesson 11", lessonTitle: "" },
  { id: "a2_l11_08", word: "countless stars", pos: "adjective", definition: "무수한", level: "Bridge A2", lesson: "Lesson 11", lessonTitle: "" },
  { id: "a2_l11_09", word: "security check", pos: "noun", definition: "보안", level: "Bridge A2", lesson: "Lesson 11", lessonTitle: "" },
  { id: "a2_l11_10", word: "organized crime", pos: "adjective", definition: "조직화된", level: "Bridge A2", lesson: "Lesson 11", lessonTitle: "" },
  { id: "a2_l11_11", word: "disciplined soldiers", pos: "adjective", definition: "잘 훈련된", level: "Bridge A2", lesson: "Lesson 11", lessonTitle: "" },
  { id: "a2_l11_12", word: "identity confusion", pos: "noun", definition: "혼란", level: "Bridge A2", lesson: "Lesson 11", lessonTitle: "" },
  { id: "a2_l11_13", word: "dramatic victory", pos: "adjective", definition: "극적인", level: "Bridge A2", lesson: "Lesson 11", lessonTitle: "" },
  { id: "a2_l11_14", word: "terrified look", pos: "adjective", definition: "공포에 질린", level: "Bridge A2", lesson: "Lesson 11", lessonTitle: "" },
  { id: "a2_l11_15", word: "trample your pride", pos: "verb", definition: "짓밟다", level: "Bridge A2", lesson: "Lesson 11", lessonTitle: "" },
  { id: "a2_l11_16", word: "modified design", pos: "adjective", definition: "수정된", level: "Bridge A2", lesson: "Lesson 11", lessonTitle: "" },
  { id: "a2_l11_17", word: "ruined city", pos: "adjective", definition: "망친", level: "Bridge A2", lesson: "Lesson 11", lessonTitle: "" },
  { id: "a2_l11_18", word: "rot teeth", pos: "verb", definition: "썩게 하다", level: "Bridge A2", lesson: "Lesson 11", lessonTitle: "" },
  { id: "a2_l11_19", word: "environmental impact", pos: "noun", definition: "영향", level: "Bridge A2", lesson: "Lesson 11", lessonTitle: "" },
  { id: "a2_l11_20", word: "natural disaster", pos: "noun", definition: "재해", level: "Bridge A2", lesson: "Lesson 11", lessonTitle: "" },
  { id: "a2_l11_21", word: "business district", pos: "noun", definition: "지구", level: "Bridge A2", lesson: "Lesson 11", lessonTitle: "" },
  { id: "a2_l11_22", word: "intellectual property", pos: "noun", definition: "재산", level: "Bridge A2", lesson: "Lesson 11", lessonTitle: "" },
  { id: "a2_l11_23", word: "accurate information", pos: "adjective", definition: "정확한", level: "Bridge A2", lesson: "Lesson 11", lessonTitle: "" },
  { id: "a2_l11_24", word: "plague outbreak", pos: "noun", definition: "전염병", level: "Bridge A2", lesson: "Lesson 11", lessonTitle: "" },
  { id: "a2_l11_25", word: "spread germs", pos: "noun", definition: "세균", level: "Bridge A2", lesson: "Lesson 11", lessonTitle: "" },
  { id: "a2_l11_26", word: "cramped kitchen", pos: "adjective", definition: "비좁은", level: "Bridge A2", lesson: "Lesson 11", lessonTitle: "" },
  { id: "a2_l11_27", word: "forest fires rage", pos: "verb", definition: "급속히 번지다", level: "Bridge A2", lesson: "Lesson 11", lessonTitle: "" },
  { id: "a2_l11_28", word: "attractive woman", pos: "adjective", definition: "매력적인", level: "Bridge A2", lesson: "Lesson 11", lessonTitle: "" },
  { id: "a2_l11_29", word: "safety measure", pos: "noun", definition: "조치", level: "Bridge A2", lesson: "Lesson 11", lessonTitle: "" },
  { id: "a2_l11_30", word: "obvious choice", pos: "adjective", definition: "당연한", level: "Bridge A2", lesson: "Lesson 11", lessonTitle: "" },
  { id: "a2_l11_31", word: "opposite direction", pos: "adjective", definition: "반대의", level: "Bridge A2", lesson: "Lesson 11", lessonTitle: "" },
  { id: "a2_l11_32", word: "triumph over evil", pos: "verb", definition: "승리하다", level: "Bridge A2", lesson: "Lesson 11", lessonTitle: "" },
  { id: "a2_l11_33", word: "thrill of victory", pos: "noun", definition: "짜릿함", level: "Bridge A2", lesson: "Lesson 11", lessonTitle: "" },
  { id: "a2_l11_34", word: "Industrial Revolution", pos: "noun", definition: "혁명", level: "Bridge A2", lesson: "Lesson 11", lessonTitle: "" },
  { id: "a2_l11_35", word: "revolt against the government", pos: "verb", definition: "반란을 일으키다", level: "Bridge A2", lesson: "Lesson 11", lessonTitle: "" },
  { id: "a2_l11_36", word: "king and royalty", pos: "noun", definition: "왕족", level: "Bridge A2", lesson: "Lesson 11", lessonTitle: "" },
  { id: "a2_l11_37", word: "public execution", pos: "noun", definition: "처형", level: "Bridge A2", lesson: "Lesson 11", lessonTitle: "" },
  { id: "a2_l11_38", word: "alternate work and rest", pos: "verb", definition: "번갈아 하다", level: "Bridge A2", lesson: "Lesson 11", lessonTitle: "" },
  { id: "a2_l11_39", word: "intense exercise", pos: "adjective", definition: "격렬한", level: "Bridge A2", lesson: "Lesson 11", lessonTitle: "" },
  { id: "a2_l11_40", word: "moderate exercise", pos: "adjective", definition: "적당한", level: "Bridge A2", lesson: "Lesson 11", lessonTitle: "" },
  { id: "a2_l11_41", word: "risk of stroke", pos: "noun", definition: "뇌졸중", level: "Bridge A2", lesson: "Lesson 11", lessonTitle: "" },
  { id: "a2_l11_42", word: "meaningless words", pos: "adjective", definition: "의미 없는", level: "Bridge A2", lesson: "Lesson 11", lessonTitle: "" },
  { id: "a2_l11_43", word: "irrelevant to the discussion", pos: "adjective", definition: "무관한", level: "Bridge A2", lesson: "Lesson 11", lessonTitle: "" },
  { id: "a2_l11_44", word: "disgust the audience", pos: "verb", definition: "혐오감을 주다", level: "Bridge A2", lesson: "Lesson 11", lessonTitle: "" },
  { id: "a2_l11_45", word: "prevailing theory", pos: "adjective", definition: "우세한", level: "Bridge A2", lesson: "Lesson 11", lessonTitle: "" },
  { id: "a2_l11_46", word: "collide with a truck", pos: "verb", definition: "충돌하다", level: "Bridge A2", lesson: "Lesson 11", lessonTitle: "" },
  { id: "a2_l11_47", word: "forceful impact", pos: "adjective", definition: "강력한", level: "Bridge A2", lesson: "Lesson 11", lessonTitle: "" },
  { id: "a2_l11_48", word: "merge two companies", pos: "verb", definition: "합치다", level: "Bridge A2", lesson: "Lesson 11", lessonTitle: "" },
  { id: "a2_l11_49", word: "debris from an explosion", pos: "noun", definition: "잔해", level: "Bridge A2", lesson: "Lesson 11", lessonTitle: "" },
  { id: "a2_l11_50", word: "gravitational pull", pos: "adjective", definition: "중력의", level: "Bridge A2", lesson: "Lesson 11", lessonTitle: "" },
  { id: "a2_l11_51", word: "orbit the sun", pos: "verb", definition: "주위를 돌다", level: "Bridge A2", lesson: "Lesson 11", lessonTitle: "" },
  { id: "a2_l11_52", word: "chemical composition", pos: "noun", definition: "구성", level: "Bridge A2", lesson: "Lesson 11", lessonTitle: "" },
  { id: "a2_l11_53", word: "student-teacher ratio", pos: "noun", definition: "비율", level: "Bridge A2", lesson: "Lesson 11", lessonTitle: "" },
  { id: "a2_l11_54", word: "argue with a friend", pos: "verb", definition: "말다툼하다", level: "Bridge A2", lesson: "Lesson 11", lessonTitle: "" },
  { id: "a2_l11_55", word: "fictional character", pos: "adjective", definition: "허구적인", level: "Bridge A2", lesson: "Lesson 11", lessonTitle: "" },
  { id: "a2_l11_56", word: "essential element", pos: "noun", definition: "요소", level: "Bridge A2", lesson: "Lesson 11", lessonTitle: "" },
  { id: "a2_l11_57", word: "first-person viewpoint", pos: "noun", definition: "시점", level: "Bridge A2", lesson: "Lesson 11", lessonTitle: "" },
  { id: "a2_l11_58", word: "technological advance", pos: "noun", definition: "발전", level: "Bridge A2", lesson: "Lesson 11", lessonTitle: "" },
  { id: "a2_l11_59", word: "special stipulation", pos: "noun", definition: "조항", level: "Bridge A2", lesson: "Lesson 11", lessonTitle: "" },
  { id: "a2_l11_60", word: "plausible theory", pos: "adjective", definition: "타당성 있는", level: "Bridge A2", lesson: "Lesson 11", lessonTitle: "" },

  // --- Bridge A2 - Lesson 12 ---
  { id: "a2_l12_01", word: "historical details", pos: "noun", definition: "상세한 정보", level: "Bridge A2", lesson: "Lesson 12", lessonTitle: "" },
  { id: "a2_l12_02", word: "tight schedule", pos: "adjective", definition: "빠듯한", level: "Bridge A2", lesson: "Lesson 12", lessonTitle: "" },
  { id: "a2_l12_03", word: "annual salary", pos: "adjective", definition: "연간의", level: "Bridge A2", lesson: "Lesson 12", lessonTitle: "" },
  { id: "a2_l12_04", word: "waste paper recycling", pos: "noun", definition: "재활용", level: "Bridge A2", lesson: "Lesson 12", lessonTitle: "" },
  { id: "a2_l12_05", word: "ground a kid for a month", pos: "verb", definition: "외출을 금지시키다", level: "Bridge A2", lesson: "Lesson 12", lessonTitle: "" },
  { id: "a2_l12_06", word: "motivate students to study", pos: "verb", definition: "의욕을 북돋다", level: "Bridge A2", lesson: "Lesson 12", lessonTitle: "" },
  { id: "a2_l12_07", word: "cake decoration", pos: "noun", definition: "장식", level: "Bridge A2", lesson: "Lesson 12", lessonTitle: "" },
  { id: "a2_l12_08", word: "trap air", pos: "verb", definition: "가두다", level: "Bridge A2", lesson: "Lesson 12", lessonTitle: "" },
  { id: "a2_l12_09", word: "similarity and difference", pos: "noun", definition: "비슷한 점", level: "Bridge A2", lesson: "Lesson 12", lessonTitle: "" },
  { id: "a2_l12_10", word: "surrounding countries", pos: "adjective", definition: "주변의", level: "Bridge A2", lesson: "Lesson 12", lessonTitle: "" },
  { id: "a2_l12_11", word: "extend the deadline", pos: "verb", definition: "연장하다", level: "Bridge A2", lesson: "Lesson 12", lessonTitle: "" },
  { id: "a2_l12_12", word: "strengthen security", pos: "verb", definition: "강화하다", level: "Bridge A2", lesson: "Lesson 12", lessonTitle: "" },
  { id: "a2_l12_13", word: "scholarly debate", pos: "noun", definition: "논쟁", level: "Bridge A2", lesson: "Lesson 12", lessonTitle: "" },
  { id: "a2_l12_14", word: "research findings", pos: "noun", definition: "연구", level: "Bridge A2", lesson: "Lesson 12", lessonTitle: "" },
  { id: "a2_l12_15", word: "school assignment", pos: "noun", definition: "과제", level: "Bridge A2", lesson: "Lesson 12", lessonTitle: "" },
  { id: "a2_l12_16", word: "imaginary animal", pos: "adjective", definition: "상상의", level: "Bridge A2", lesson: "Lesson 12", lessonTitle: "" },
  { id: "a2_l12_17", word: "convey meaning", pos: "verb", definition: "전달하다", level: "Bridge A2", lesson: "Lesson 12", lessonTitle: "" },
  { id: "a2_l12_18", word: "thoughtful advice", pos: "adjective", definition: "사려 깊은", level: "Bridge A2", lesson: "Lesson 12", lessonTitle: "" },
  { id: "a2_l12_19", word: "UN delegate", pos: "noun", definition: "대표", level: "Bridge A2", lesson: "Lesson 12", lessonTitle: "" },
  { id: "a2_l12_20", word: "emphasis of research", pos: "noun", definition: "주안점", level: "Bridge A2", lesson: "Lesson 12", lessonTitle: "" },
  { id: "a2_l12_21", word: "sacred writings", pos: "adjective", definition: "신성한", level: "Bridge A2", lesson: "Lesson 12", lessonTitle: "" },
  { id: "a2_l12_22", word: "convince a customer", pos: "verb", definition: "설득하다", level: "Bridge A2", lesson: "Lesson 12", lessonTitle: "" },
  { id: "a2_l12_23", word: "comfort of a bed", pos: "noun", definition: "편안함", level: "Bridge A2", lesson: "Lesson 12", lessonTitle: "" },
  { id: "a2_l12_24", word: "top priority", pos: "noun", definition: "우선 사항", level: "Bridge A2", lesson: "Lesson 12", lessonTitle: "" },
  { id: "a2_l12_25", word: "expand business", pos: "verb", definition: "확장하다", level: "Bridge A2", lesson: "Lesson 12", lessonTitle: "" },
  { id: "a2_l12_26", word: "desperate call for help", pos: "adjective", definition: "절박한", level: "Bridge A2", lesson: "Lesson 12", lessonTitle: "" },
  { id: "a2_l12_27", word: "exclude a player from the list", pos: "verb", definition: "제외하다", level: "Bridge A2", lesson: "Lesson 12", lessonTitle: "" },
  { id: "a2_l12_28", word: "ridicule and mock", pos: "verb", definition: "조롱하다", level: "Bridge A2", lesson: "Lesson 12", lessonTitle: "" },
  { id: "a2_l12_29", word: "military strategist", pos: "noun", definition: "전략가", level: "Bridge A2", lesson: "Lesson 12", lessonTitle: "" },
  { id: "a2_l12_30", word: "launch an attack", pos: "verb", definition: "개시하다", level: "Bridge A2", lesson: "Lesson 12", lessonTitle: "" },
  { id: "a2_l12_31", word: "hero and heroine", pos: "noun", definition: "여걸", level: "Bridge A2", lesson: "Lesson 12", lessonTitle: "" },
  { id: "a2_l12_32", word: "body's metabolism", pos: "noun", definition: "신진대사", level: "Bridge A2", lesson: "Lesson 12", lessonTitle: "" },
  { id: "a2_l12_33", word: "excess supply", pos: "adjective", definition: "초과의", level: "Bridge A2", lesson: "Lesson 12", lessonTitle: "" },
  { id: "a2_l12_34", word: "success factor", pos: "noun", definition: "요인", level: "Bridge A2", lesson: "Lesson 12", lessonTitle: "" },
  { id: "a2_l12_35", word: "tricky subject", pos: "adjective", definition: "까다로운", level: "Bridge A2", lesson: "Lesson 12", lessonTitle: "" },
  { id: "a2_l12_36", word: "rare species", pos: "noun", definition: "종", level: "Bridge A2", lesson: "Lesson 12", lessonTitle: "" },
  { id: "a2_l12_37", word: "prehistoric stone tool", pos: "adjective", definition: "선사시대의", level: "Bridge A2", lesson: "Lesson 12", lessonTitle: "" },
  { id: "a2_l12_38", word: "extinct dinosaurs", pos: "adjective", definition: "멸종된", level: "Bridge A2", lesson: "Lesson 12", lessonTitle: "" },
  { id: "a2_l12_39", word: "wild speculation", pos: "noun", definition: "추측", level: "Bridge A2", lesson: "Lesson 12", lessonTitle: "" },
  { id: "a2_l12_40", word: "prominent scholar", pos: "adjective", definition: "저명한", level: "Bridge A2", lesson: "Lesson 12", lessonTitle: "" },
  { id: "a2_l12_41", word: "reach a consensus", pos: "noun", definition: "의견 일치", level: "Bridge A2", lesson: "Lesson 12", lessonTitle: "" },
  { id: "a2_l12_42", word: "radical difference", pos: "adjective", definition: "근본적인", level: "Bridge A2", lesson: "Lesson 12", lessonTitle: "" },
  { id: "a2_l12_43", word: "wildlife habitat", pos: "noun", definition: "서식지", level: "Bridge A2", lesson: "Lesson 12", lessonTitle: "" },
  { id: "a2_l12_44", word: "adapt to the new school", pos: "verb", definition: "적응하다", level: "Bridge A2", lesson: "Lesson 12", lessonTitle: "" },
  { id: "a2_l12_45", word: "archaeological dig", pos: "adjective", definition: "고고학의", level: "Bridge A2", lesson: "Lesson 12", lessonTitle: "" },
  { id: "a2_l12_46", word: "government critic", pos: "noun", definition: "비판자", level: "Bridge A2", lesson: "Lesson 12", lessonTitle: "" },
  { id: "a2_l12_47", word: "overstate the benefits", pos: "verb", definition: "과장하다", level: "Bridge A2", lesson: "Lesson 12", lessonTitle: "" },
  { id: "a2_l12_48", word: "tribal society", pos: "adjective", definition: "부족의", level: "Bridge A2", lesson: "Lesson 12", lessonTitle: "" },
  { id: "a2_l12_49", word: "spiritual leader", pos: "adjective", definition: "정신적인", level: "Bridge A2", lesson: "Lesson 12", lessonTitle: "" },
  { id: "a2_l12_50", word: "religious ritual", pos: "noun", definition: "의식", level: "Bridge A2", lesson: "Lesson 12", lessonTitle: "" },
  { id: "a2_l12_51", word: "wedding celebration", pos: "noun", definition: "축하 행사", level: "Bridge A2", lesson: "Lesson 12", lessonTitle: "" },
  { id: "a2_l12_52", word: "wedding ceremony", pos: "noun", definition: "의식", level: "Bridge A2", lesson: "Lesson 12", lessonTitle: "" },
  { id: "a2_l12_53", word: "rice harvest", pos: "noun", definition: "수학", level: "Bridge A2", lesson: "Lesson 12", lessonTitle: "" },
  { id: "a2_l12_54", word: "wealth and privilege", pos: "noun", definition: "특권", level: "Bridge A2", lesson: "Lesson 12", lessonTitle: "" },
  { id: "a2_l12_55", word: "respect and honor", pos: "noun", definition: "명예", level: "Bridge A2", lesson: "Lesson 12", lessonTitle: "" },
  { id: "a2_l12_56", word: "identity theft", pos: "noun", definition: "신분", level: "Bridge A2", lesson: "Lesson 12", lessonTitle: "" },
  { id: "a2_l12_57", word: "ancient wisdom", pos: "noun", definition: "지혜", level: "Bridge A2", lesson: "Lesson 12", lessonTitle: "" },
  { id: "a2_l12_58", word: "career guidance", pos: "noun", definition: "지도", level: "Bridge A2", lesson: "Lesson 12", lessonTitle: "" },
  { id: "a2_l12_59", word: "carve a stone statue", pos: "verb", definition: "조각하다", level: "Bridge A2", lesson: "Lesson 12", lessonTitle: "" },
  { id: "a2_l12_60", word: "industrial modernization", pos: "noun", definition: "현대화", level: "Bridge A2", lesson: "Lesson 12", lessonTitle: "" }
];

